### ISSUE TITLE
Docker hub doesn't point here

### ISSUE THREAD

**Issue by bryceschober** [balena-io-library/resin-rpi-raspbian#74]
I went to the [docker hub site](https://hub.docker.com/r/resin/rpi-raspbian/) today and went to check the details of the image, and both the manifest and repository links go to the main [resin-io-library/official-images](https://github.com/resin-io-library/official-images) repository, which superficially knows nothing about this particular set of images for raspbian.

**Comment by FibreFoX** [comment]
Even the link inside the Readme is wrong:
https://hub.docker.com/r/balena/rpi-raspbian/ -> 404

**Comment by snowytoxa** [comment]
this one works
https://registry.hub.docker.com/r/balenalib/rpi-raspbian

**Comment by vipulgupta2048** [comment]
Thanks for opening the issue. The readme points to the right link now, so we can close this issue. Let us know if you see any inconsistencies anywhere.

**Comment by nghiant2710** [comment]
Sorry for the inconvenience, the dockerhub description is updated!
