### ISSUE TITLE
Strech?

### ISSUE THREAD

**Issue by rmoriz** [balena-io-library/resin-rpi-raspbian#87]
Can we get a stretch based image?

**Comment by nghiant2710** [comment]
@rmoriz, we do have the stretch base image, you can pull `balenalib/rpi-raspbian:stretch`

**Comment by rmoriz** [comment]
thanks. I was trying to build the image myself and found a reference to jessie in the Dockerfile https://github.com/balena-io-library/resin-rpi-raspbian/blob/master/Dockerfile
