### ISSUE TITLE
Support Debian Buster

### ISSUE THREAD

**Issue by stv0g** [balena-io-library/resin-rpi-raspbian#94]
The newest Raspian images (since June 2019) are based on Debian Buster.

Can we create another tag for this image based on Buster?

**Comment by nghiant2710** [comment]
hey @stv0g, we do provide the Buster image as `balenalib/rpi-raspbian:buster`.

The latest tag is `stretch` since it's current Debian stable distribution.

**Comment by stv0g** [comment]
Thanks :) Last time I checked, I was missing this tag
